receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 512
    timeout: 5s
  resource/logs:
    attributes:
      - key: deployment.environment
        value: "${DEPLOYMENT_ENVIRONMENT}"
        action: upsert
  attributes/logs:
    actions:
      - key: fluent.tag
        action: delete

exporters:
  otlphttp:
    endpoint: http://apm-server:8200
  debug:
    verbosity: basic
  elasticsearch:
    endpoints: [http://elasticsearch:9200]
    logs_index: logs-app-default
    mapping:
      mode: ecs
    flush:
      bytes: 5242880
      interval: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]
    logs:
      receivers: [fluentforward]
      processors: [memory_limiter, resource/logs, attributes/logs, batch]
      exporters: [elasticsearch]
