[SERVICE]
    flush                     1
    log_level                 info
    parsers_file              parsers.conf
    storage.path              /fluent-bit/db/storage
    storage.sync              normal
    storage.checksum          off
    storage.max_chunks_up     128
    storage.backlog.mem_limit 5M

[INPUT]
    name              tail
    path              /var/lib/docker/containers/*/*-json.log
    tag               app.docker
    parser            docker
    read_from_head    on
    db                /fluent-bit/db/tail.db
    buffer_max_size   256k
    skip_long_lines   on

# 앱 컨테이너만 통과 (label log_collect=true)
[FILTER]
    name    grep
    match   app.*
    regex   $attrs['log_collect'] true

# Winston JSON 파싱
[FILTER]
    name         parser
    match        app.*
    key_name     log
    parser       app_json
    reserve_data off

[OUTPUT]
    name                     forward
    match                    app.*
    host                     otel-collector
    port                     8006
