[SERVICE]
    flush        1
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name         http
    listen       0.0.0.0
    port         24224
    tag          app.logs

# --- ECS field rename ---
[FILTER]
    name         modify
    match        *
    rename       level log.level
    rename       service service.name
    rename       context log.logger
    rename       trace_id trace.id
    rename       span_id span.id
    rename       hostname host.name

[OUTPUT]
    name            es
    match           *
    host            elasticsearch
    port            9200
    index           logs-app-default
    suppress_type_name on
    generate_id     on
    trace_error     on
